### ISSUE TITLE
Static IP assignment can't be run on the VPN

### ISSUE THREAD

**Issue by bcomnes** [PSU-OIT-ARC/vagrant-manifest#5]
...and forwarding a port does not seem to work either.  I was trying to get a dev environment for traq working this weekend, but kept running into issues talking to the ldap server.  Thinking the VPN might be required to make off campus queries, I found out that the Anyconnect software blocks local connections to 10.0.0.10 when connected.

**Comment by wylee** [comment]
Closed because this ticket is a year old and things seem to work now.

**Comment by bcomnes** [comment]
Womp.  Fair enough.
